# Generated by Django 4.1.3 on 2022-11-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orederdetail',
            name='oredered_date',
        ),
    ]
