# Generated by Django 4.1.3 on 2022-11-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0003_remove_orederdetail_oredered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='lexiconapp.customer'),
        ),
        migrations.AlterField(
            model_name='orederdetail',
            name='customer',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='lexiconapp.customer'),
        ),
    ]
