# Generated by Django 4.1.3 on 2022-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0004_alter_basket_customer_alter_orederdetail_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orederdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orederdetail',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='OrederDetail',
        ),
    ]
